#SETUP FILES
ROBOTFILE = 'LoCoQuad.botfile.txt'

#Actuators or Sensors
ACC = 0
SEN = 1
BOTH = 2

#Number of parameters that define an Actuator or a Sensor
N_ACC_PARAM = 9
N_SEN_PARAM = 4

#Factor for movemente speed scaling
SPEED_FACTOR = 10.0

#Scaling factor from angles to pulses
SCALE_ACC = 11
CNT_ACC = 500

#GENERAL FINITE STATE MACHINE
#States
INIT = 0
REST = 1
EXPLORE = 2
SHOWOFF = 3
PHOTO = 4

#EXPLORE FINITE STATE MACHINE
#States
GETDATA = 0
PROCESSDATA = 1
MOVE = 2
RECONTURN = 3

#MOVES CODES
NONE = 0
WF = 1
WB = 2
WR = 3
WL = 4
TR = 5
TL = 6
FLAT = 7
STAND = 8

# GPIO Pins
TRIG = 27
ECHO = 22

#IMU REGISTERS
#some MPU6050 Registers and their Address
PWR_MGMT_1 = 0x6B
SMPLRT_DIV = 0x19
CONFIG = 0x1A
GYRO_CONFIG = 0x1B
INT_ENABLE = 0x38
ACCEL_XOUT_H = 0x3B
ACCEL_YOUT_H = 0x3D
ACCEL_ZOUT_H = 0x3F
GYRO_XOUT_H = 0x43
GYRO_YOUT_H = 0x45
GYRO_ZOUT_H = 0x47





# VISION TOOLBOX CONFIGURATION
# ----------------------------

#CAMRA CALIBRATION
CALIBRATION_PATH = "./CalibrationFiles"
OUTPUT_PATH = "./Captures/"

RING_SIZE = 4 
NUMBER_FACES = 4 
NUMBER_TAG_SICES = 2 
NUM_TAGS_SIZE1 = 2
NUM_TAGS_SIZE2 = 3

TAG1_SIZE = 5		#- [cm]
TAG2_SIZE = 10		#- [cm]

A4_WIDTH = 29.7  	#- [cm]
A4_HEIGHT = 21.0 	#- [cm]

SMALL_TAG_CODE = 1
BIG_TAG_CODE = 0

#LOGING
WRITE_LOG_FILE = False

#CONSTANTS
PI = 3.1415926536
PI2 = 1.5707963268

#LIMIT NUMBER OF TAGS PROCESSED ON EACH FRAME
TAG_NUMBER_LIMITED = False
MAX_TAG_NUMBER = 2


#STATE TIMES
EXPLORATION_TIME = 45
REST_TIME = 35